// AdminTable

export const LOAD_TABLEDATA = 'LOAD_TABLEDATA';
export const LOAD_TABLEDATA_SUCCESS = 'LOAD_TABLEDATA_SUCCESS';
export const LOAD_TABLEDATA_FAIL = 'LOAD_TABLEDATA_FAIL';

export const LOAD_TABLECOLUMNS = 'LOAD_TABLECOLUMNS';
export const LOAD_TABLECOLUMNS_SUCCESS = 'LOAD_TABLECOLUMNS_SUCCESS';
export const LOAD_TABLECOLUMNS_FAIL = 'LOAD_TABLECOLUMNS_FAIL';

export const DELETE_TABLEDATA = 'DELETE_TABLEDATA';
export const DELETE_TABLEDATA_SUCCESS = 'DELETE_TABLEDATA_SUCCESS';
export const DELETE_TABLEDATA_FAIL = 'DELETE_TABLEDATA_FAIL';

export const ENABLE_TABLEDATA_SUCCESS = 'ENABLE_TABLEDATA_SUCCESS';
export const ENABLE_TABLEDATA_FAIL = 'ENABLE_TABLEDATA_FAIL';

export const TABLEDATA_UPDATE_REQUEST = 'TABLEDATA_UPDATE_REQUEST';
export const TABLEDATA_UPDATE_SUCCESS = 'TABLEDATA_UPDATE_SUCCESS';
export const TABLEDATA_UPDATE_FAILURE = 'TABLEDATA_UPDATE_FAILURE';

export const CHANGE_SELECTED_ROWS = 'CHANGE_SELECTED_ROWS';


// load child subject talble columns
export const LOAD_CHILDSUBJECTFIELDS = 'LOAD_CHILDSUBJECTFIELDS';
export const LOAD_CHILDSUBJECTFIELDS_SUCCESS = 'LOAD_CHILDSUBJECTFIELDS_SUCCESS';
export const LOAD_CHILDSUBJECTFIELDS_FAIL = 'LOAD_CHILDSUBJECTFIELDS_FAIL';

// 对话框

// EDIT
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';
export const EDIT_DIALOG_CLOSE = 'EDIT_DIALOG_CLOSE';

// ADD CHILD
export const SHOW_CHILD_DIALOG = 'SHOW_CHILD_DIALOG';
export const CHILD_DIALOG_CLOSE = 'CHILD_DIALOG_CLOSE';

// CREATE
export const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG';
export const HIDE_CREATE_DIALOG = 'HIDE_CREATE_DIALOG';

// AdminEditForm

// EDIT
export const ARCH_INIT_EDIT_FORM_DATA = 'ARCH_INIT_EDIT_FORM_DATA';
export const UPDATE_EDIT_FORM_FIELD_VALUE = 'UPDATE_EDIT_FORM_FIELD_VALUE';

export const SUBMIT_EDIT_FORM = 'SUBMIT_EDIT_FORM';
export const SUBMIT_EDIT_FORM_SUCCESS = 'SUBMIT_EDIT_FORM_SUCCESS';
export const SUBMIT_EDIT_FORM_FAIL = 'SUBMIT_EDIT_FORM_FAIL';

// ADD CHILD
export const ARCH_INIT_CHILD_FORM_DATA = 'ARCH_INIT_CHILD_FORM_DATA';
export const UPDATE_CHILD_FORM_FIELD_VALUE = 'UPDATE_CHILD_FORM_FIELD_VALUE';

export const SUBMIT_CHILD_FORM = 'SUBMIT_CHILD_FORM';
export const SUBMIT_CHILD_FORM_SUCCESS = 'SUBMIT_CHILD_FORM_SUCCESS';
export const SUBMIT_CHILD_FORM_FAIL = 'SUBMIT_CHILD_FORM_FAIL';

// CREATE
export const INIT_CREATE_FORM_DATA = 'INIT_CREATE_FORM_DATA';
export const UPDATE_CREATE_FORM_FIELD_VALUE = 'UPDATE_CREATE_FORM_FIELD_VALUE';

export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM';
export const SUBMIT_CREATE_FORM_SUCCESS = 'SUBMIT_CREATE_FORM_SUCCESS';
export const SUBMIT_CREATE_FORM_FAIL = 'SUBMIT_CREATE_FORM_FAIL';

// 页面中的消息框

export const ERROR_MESSAGES_UPDATE = 'ERROR_MESSAGES_UPDATE';

export const SHOW_ADMIN_ALERT = 'SHOW_ADMIN_ALERT';
export const HIDE_ADMIN_ALERT = 'HIDE_ADMIN_ALERT';

// 对话框中的消息框

export const FORM_ALERT_OPEN = 'FORM_ALERT_OPEN';
export const FORM_ALERT_CLOSE = 'FORM_ALERT_CLOSE';

// 跳转到页

export const GOTO_PAGE = 'GOTO_PAGE';

// 修复refer fields

export const REFER_FIELDS_UPDATE = 'REFER_FIELDS_UPDATE';

// 提示框信息
export const HIDE_MESSAGE_TIPS = 'HIDE_MESSAGE_TIPS';

// 修改查询条件
export const CONDITIONS_UPDATE = 'CONDITIONS_UPDATE';
