// Arch setting

export const ARCH_SETTING_REQUEST = 'ARCH_SETTING_REQUEST';
export const ARCH_SETTING_SUCCESS = 'ARCH_SETTING_SUCCESS';
export const ARCH_SETTING_FAILURE = 'ARCH_SETTING_FAILURE';

export const ARCH_SETTING_CONFIG_REQUEST = 'ARCH_SETTING_CONFIG_REQUEST';
export const ARCH_SETTING_CONFIG_SUCCESS = 'ARCH_SETTING_CONFIG_SUCCESS';
export const ARCH_SETTING_CONFIG_FAILURE = 'ARCH_SETTING_CONFIG_FAILURE';

export const ARCH_SETTING_DELETE_REQUEST  = 'ARCH_SETTING_DELETE_REQUEST';
export const ARCH_SETTING_DELETE_SUCCESS  = 'ARCH_SETTING_DELETE_SUCCESS';
export const ARCH_SETTING_DELETE_FAILURE  = 'ARCH_SETTING_DELETE_FAILURE';

export const CHANGE_SELECTED_ROWS = 'CHANGE_SELECTED_ROWS';

// AdminEditDialog

// EDIT
export const ARCH_SETTING_EDIT_DIALOG_SHOW = 'ARCH_SETTING_EDIT_DIALOG_SHOW';
export const ARCH_SETTING_EDIT_DIALOG_HIDE = 'ARCH_SETTING_EDIT_DIALOG_HIDE';

// CREATE
export const ARCH_SETTING_CREATE_DIALOG_SHOW = 'ARCH_SETTING_CREATE_DIALOG_SHOW';
export const ARCH_SETTING_CREATE_DIALOG_HIDE = 'ARCH_SETTING_CREATE_DIALOG_HIDE';

// AdminEditForm

// EDIT
export const INIT_EDIT_FORM_DATA = 'INIT_EDIT_FORM_DATA';
export const UPDATE_EDIT_FORM_FIELD_VALUE = 'UPDATE_EDIT_FORM_FIELD_VALUE';

export const SUBMIT_EDIT_FORM = 'SUBMIT_EDIT_FORM';
export const SUBMIT_EDIT_FORM_SUCCESS = 'SUBMIT_EDIT_FORM_SUCCESS';
export const SUBMIT_EDIT_FORM_FAIL = 'SUBMIT_EDIT_FORM_FAIL';

// CREATE
export const INIT_CREATE_FORM_DATA = 'INIT_CREATE_FORM_DATA';
export const UPDATE_CREATE_FORM_FIELD_VALUE = 'UPDATE_CREATE_FORM_FIELD_VALUE';

export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM';
export const SUBMIT_CREATE_FORM_SUCCESS = 'SUBMIT_CREATE_FORM_SUCCESS';
export const SUBMIT_CREATE_FORM_FAIL = 'SUBMIT_CREATE_FORM_FAIL';

// AdminAlert

export const ARCH_SETTING_ADMIN_ALERT_SHOW = 'ARCH_SETTING_ADMIN_ALERT_SHOW';
export const ARCH_SETTING_ADMIN_ALERT_HIDE = 'ARCH_SETTING_ADMIN_ALERT_HIDE';
