export const INIT_DEMO_EDIT_FORM1_DATA = 'INIT_DEMO_EDIT_FORM1_DATA';
export const UPDATE_DEMO_EDIT_FORM1_FIELD_VALUE = 'UPDATE_DEMO_EDIT_FORM1_FIELD_VALUE';

export const INIT_DEMO_EDIT_FORM2_DATA = 'INIT_DEMO_EDIT_FORM2_DATA';
export const UPDATE_DEMO_EDIT_FORM2_FIELD_VALUE = 'UPDATE_DEMO_EDIT_FORM2_FIELD_VALUE';
