// Permission

export const PERMISSION_REQUEST = 'PERMISSION_REQUEST';
export const PERMISSION_SUCCESS = 'PERMISSION_SUCCESS';
export const PERMISSION_FAILURE = 'PERMISSION_FAILURE';

export const PERMISSION_DELETE_REQUEST  = 'PERMISSION_DELETE_REQUEST';
export const PERMISSION_DELETE_SUCCESS  = 'PERMISSION_DELETE_SUCCESS';
export const PERMISSION_DELETE_FAILURE  = 'PERMISSION_DELETE_FAILURE';

export const CHANGE_SELECTED_ROWS = 'CHANGE_SELECTED_ROWS';

// AdminEditDialog

// EDIT
export const PERMISSION_EDIT_DIALOG_SHOW = 'PERMISSION_EDIT_DIALOG_SHOW';
export const PERMISSION_EDIT_DIALOG_HIDE = 'PERMISSION_EDIT_DIALOG_HIDE';

// CREATE
export const PERMISSION_CREATE_DIALOG_SHOW = 'PERMISSION_CREATE_DIALOG_SHOW';
export const PERMISSION_CREATE_DIALOG_HIDE = 'PERMISSION_CREATE_DIALOG_HIDE';

// AdminEditForm

// EDIT
export const INIT_EDIT_FORM_DATA = 'INIT_EDIT_FORM_DATA';
export const UPDATE_EDIT_FORM_FIELD_VALUE = 'UPDATE_EDIT_FORM_FIELD_VALUE';

export const SUBMIT_EDIT_FORM = 'SUBMIT_EDIT_FORM';
export const SUBMIT_EDIT_FORM_SUCCESS = 'SUBMIT_EDIT_FORM_SUCCESS';
export const SUBMIT_EDIT_FORM_FAIL = 'SUBMIT_EDIT_FORM_FAIL';

// CREATE
export const INIT_CREATE_FORM_DATA = 'INIT_CREATE_FORM_DATA';
export const UPDATE_CREATE_FORM_FIELD_VALUE = 'UPDATE_CREATE_FORM_FIELD_VALUE';

export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM';
export const SUBMIT_CREATE_FORM_SUCCESS = 'SUBMIT_CREATE_FORM_SUCCESS';
export const SUBMIT_CREATE_FORM_FAIL = 'SUBMIT_CREATE_FORM_FAIL';

// AdminAlert

export const PERMISSION_ADMIN_ALERT_SHOW = 'PERMISSION_ADMIN_ALERT_SHOW';
export const PERMISSION_ADMIN_ALERT_HIDE = 'PERMISSION_ADMIN_ALERT_HIDE';
