// Role

export const ROLE_REQUEST = 'ROLE_REQUEST';
export const ROLE_SUCCESS = 'ROLE_SUCCESS';
export const ROLE_FAILURE = 'ROLE_FAILURE';

export const ROLE_DELETE_REQUEST  = 'ROLE_DELETE_REQUEST';
export const ROLE_DELETE_SUCCESS  = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_FAILURE  = 'ROLE_DELETE_FAILURE';

export const CHANGE_SELECTED_ROWS = 'CHANGE_SELECTED_ROWS';

// AdminEditDialog

// EDIT
export const SHOW_EDIT_DIALOG = 'SHOW_EDIT_DIALOG';
export const HIDE_EDIT_DIALOG = 'HIDE_EDIT_DIALOG';

// CREATE
export const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG';
export const HIDE_CREATE_DIALOG = 'HIDE_CREATE_DIALOG';

// AdminEditForm

// EDIT
export const INIT_EDIT_FORM_DATA = 'INIT_EDIT_FORM_DATA';
export const UPDATE_EDIT_FORM_FIELD_VALUE = 'UPDATE_EDIT_FORM_FIELD_VALUE';

export const SUBMIT_EDIT_FORM = 'SUBMIT_EDIT_FORM';
export const SUBMIT_EDIT_FORM_SUCCESS = 'SUBMIT_EDIT_FORM_SUCCESS';
export const SUBMIT_EDIT_FORM_FAIL = 'SUBMIT_EDIT_FORM_FAIL';

// CREATE
export const INIT_CREATE_FORM_DATA = 'INIT_CREATE_FORM_DATA';
export const UPDATE_CREATE_FORM_FIELD_VALUE = 'UPDATE_CREATE_FORM_FIELD_VALUE';

export const SUBMIT_CREATE_FORM = 'SUBMIT_CREATE_FORM';
export const SUBMIT_CREATE_FORM_SUCCESS = 'SUBMIT_CREATE_FORM_SUCCESS';
export const SUBMIT_CREATE_FORM_FAIL = 'SUBMIT_CREATE_FORM_FAIL';

// AdminAlert

export const SHOW_ADMIN_ALERT = 'SHOW_ADMIN_ALERT';
export const HIDE_ADMIN_ALERT = 'HIDE_ADMIN_ALERT';
